name: build
on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test & lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # gives the commit message linter access to all previous commits

      - name: Commit lint
        if: ${{ matrix.python == '3.10' && github.ref == 'refs/heads/main' }}
        uses: wagoid/commitlint-github-action@v4

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install deps with ${{ matrix.python }}
        run: pip install ".[test, ci]"

      - name: Lint with ${{ matrix.python }}
        if: ${{ matrix.python == '3.10' }}
        run: make lint

      - name: Test with ${{ matrix.python }}
        env:
          TEST_ORIGINAL_HOST: ${{secrets.TEST_ORIGINAL_HOST}}
          TEST_ORIGINAL_API_VERSION: ${{secrets.TEST_ORIGINAL_API_VERSION}}
          TEST_API_KEY: ${{secrets.TEST_API_KEY}}
          TEST_API_SECRET: ${{secrets.TEST_API_SECRET}}
          TEST_APP_USER_UID: ${{secrets.TEST_APP_USER_UID}}
          TEST_APP_USER_EMAIL: ${{secrets.TEST_APP_USER_EMAIL}}
          TEST_APP_USER_CLIENT_ID: ${{secrets.TEST_APP_USER_CLIENT_ID}}
          TEST_APP_COLLECTION_UID: ${{secrets.TEST_APP_COLLECTION_UID}}
          TEST_ASSET_UID: ${{secrets.TEST_ASSET_UID}}
          TEST_TRANSFER_TO_WALLET_ADDRESS: ${{secrets.TEST_TRANSFER_TO_WALLET_ADDRESS}}
          TEST_TRANSFER_TO_USER_UID: ${{secrets.TEST_TRANSFER_TO_USER_UID}}
          TEST_TRANSFER_UID: ${{secrets.TEST_TRANSFER_UID}}
          TEST_BURN_UID: ${{secrets.TEST_BURN_UID}}
          TEST_APP_REWARD_UID: ${{secrets.TEST_APP_REWARD_UID}}
          TEST_ALLOCATION_UID: ${{secrets.TEST_ALLOCATION_UID}}
          TEST_CLAIM_UID: ${{secrets.TEST_CLAIM_UID}}
          TEST_CLAIM_TO_ADDRESS: ${{secrets.TEST_CLAIM_TO_ADDRESS}}
          TEST_ACCEPTANCE_CHAIN_ID: ${{secrets.TEST_ACCEPTANCE_CHAIN_ID}}
          TEST_ACCEPTANCE_NETWORK: ${{secrets.TEST_ACCEPTANCE_NETWORK}}
          TEST_MULTI_CHAIN_API_KEY: ${{secrets.TEST_MULTI_CHAIN_API_KEY}}
          TEST_MULTI_CHAIN_API_SECRET: ${{secrets.TEST_MULTI_CHAIN_API_SECRET}}
          TEST_MULTI_CHAIN_COLLECTION_UID: ${{secrets.TEST_MULTI_CHAIN_COLLECTION_UID}}
          TEST_MULTI_CHAIN_TRANSFER_TO_USER_WALLET: ${{secrets.TEST_MULTI_CHAIN_TRANSFER_TO_USER_WALLET}}
          TEST_MULTI_CHAIN_TRANSFER_TO_USER_UID: ${{secrets.TEST_MULTI_CHAIN_TRANSFER_TO_USER_UID}}
          PYTHONPATH: ${{ github.workspace }}
        run: make test
