name: build
on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🧪 Test & lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # gives the commit message linter access to all previous commits

      - name: Commit lint
        if: ${{ matrix.python == '3.7' && github.ref == 'refs/heads/main' }}
        uses: wagoid/commitlint-github-action@v4

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install deps with ${{ matrix.python }}
        run: pip install ".[test, ci]"

      - name: Lint with ${{ matrix.python }}
        if: ${{ matrix.python == '3.7' }}
        run: make lint

      - name: Test with ${{ matrix.python }}
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          PYTHONPATH: ${{ github.workspace }}
        run: make test
